name: Nuke CICD Pipeline
on:
  push:
    branches:
    - prerelease
    - master
    tags:
    - bump-*
  pull_request:
    branches:
    - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  PRE_SETUP:
    name: Pre Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: NUKE_RUN
      name: Run Nuke PipelinePreSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      NUKE_PRE_SETUP: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP }}
      NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CONDITION }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_RUNS_ON }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_RUN_SCRIPT }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CACHE_KEY }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CONDITION }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_RUNS_ON }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_RUN_SCRIPT }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CACHE_KEY }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CONDITION }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_RUNS_ON }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_RUN_SCRIPT }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CACHE_KEY }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
  TRANSACTIONHELPERSTEST:
    name: Test - transaction_helpers (TransactionHelpersTest)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineTest
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_RUN_SCRIPT }} PipelineTest --args "TransactionHelpersTest"
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSTEST_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  TRANSACTIONHELPERSBUILD:
    name: Build - transaction_helpers (TransactionHelpersBuild)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineBuild
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_RUN_SCRIPT }} PipelineBuild --args "TransactionHelpersBuild"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: transaction_helpers___TRANSACTIONHELPERSBUILD
        path: ./.nuke/output/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - TRANSACTIONHELPERSTEST
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSBUILD_CONDITION == 'true' && needs.TRANSACTIONHELPERSTEST.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  TRANSACTIONHELPERSPUBLISH:
    name: Publish - transaction_helpers (TransactionHelpersPublish)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts
        pattern: transaction_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelinePublish
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_RUN_SCRIPT }} PipelinePublish --args "TransactionHelpersPublish"
    needs:
    - PRE_SETUP
    - TRANSACTIONHELPERSBUILD
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TRANSACTIONHELPERSPUBLISH_CONDITION == 'true' && needs.TRANSACTIONHELPERSTEST.result != 'failure' && needs.TRANSACTIONHELPERSBUILD.result != 'failure'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  POST_SETUP:
    name: Post Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts
    - name: Run Nuke PipelinePostSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePostSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
    - PRE_SETUP
    - TRANSACTIONHELPERSTEST
    - TRANSACTIONHELPERSBUILD
    - TRANSACTIONHELPERSPUBLISH
    if: success() || failure() || always()
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
      NUKE_RUN_RESULT_GITHUB_TRANSACTIONHELPERSTEST: ${{ needs.TRANSACTIONHELPERSTEST.result }}
      NUKE_RUN_RESULT_GITHUB_TRANSACTIONHELPERSBUILD: ${{ needs.TRANSACTIONHELPERSBUILD.result }}
      NUKE_RUN_RESULT_GITHUB_TRANSACTIONHELPERSPUBLISH: ${{ needs.TRANSACTIONHELPERSPUBLISH.result }}
env:
  NUKE_NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
  NUKE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
